export ASG_NAME=${ASG_NAME:-dynomite}
export EC2_REGION=${EC2_REGION:-us-east-1}
export AUTO_SCALE_GROUP=${AUTO_SCALE_GROUP:-dynomite}
export DM_ACL_GROUPNAME=${DM_ACL_GROUPNAME:-dynomite}
export DM_DATACENTER=${DM_DATACENTER:-us-east-1}
export DM_RACK=${DM_RACK:-us-east-1b}
export DM_USE_ASG_FOR_RACK_NAME${DM_USE_ASG_FOR_RACK_NAME:-false}
export DM_DYNOMITE_MEMBERSHIP_YAML=${DM_DYNOMITE_MEMBERSHIP_YAML:-/etc/dynomite-manager/membership.yml}

export DM_DYNOMITE_INSTALL_DIR=${DM_DYNOMITE_INSTALL_DIR:-/home/dynomite/}

export DM_DYNOMITE_START_SCRIPT=${DM_DYNOMITE_START_SCRIPT:-/usr/sbin/service dynomite start}

export DM_DYNOMITE_STOP_SCRIPT=${DM_DYNOMITE_STOP_SCRIPT:-/usr/sbin/service dynomite stop}

export DM_DYNOMITE_CLUSTER_NAME=${DM_DYNOMITE_CLUSTER_NAME:-dynomite}

export DM_DYNOMITE_SEED_PROVIDER=${DM_DYNOMITE_SEED_PROVIDER:-florida_provider}

export DM_DYNOMITE_CLIENT_PORT=${DM_DYNOMITE_CLIENT_PORT:-8102}

export DM_DYNOMITE_PEER_PORT=${DM_DYNOMITE_PEER_PORT:-8101}

export DM_DYNOMITE_GOSSIP_INTERVAL=${DM_DYNOMITE_GOSSIP_INTERVAL:-10000}

export DM_DYNOMITE_HASH_ALGORITHM=${DM_DYNOMITE_HASH_ALGORITHM:-murmur}

export DM_DYNOMITE_STORAGE_PRECONNECT=${DM_DYNOMITE_STORAGE_PRECONNECT:-true}

export DM_DYNOMITE_MULTI_DC=${DM_DYNOMITE_MULTI_DC:-true}

export DM_DYNOMITE_MBUF_SIZE=${DM_DYNOMITE_MBUF_SIZE:-16384}

export DM_DYNOMITE_MAX_ALLOCATED_MESSAGES=${DM_DYNOMITE_MAX_ALLOCATED_MESSAGES:-200000}

export DM_DYNOMITE_PROCESS_NAME=${DM_DYNOMITE_PROCESS_NAME:-dynomite}

export DM_DYNOMITE_YAML=${DM_DYNOMITE_YAML:-/etc/dynomite/dynomite.yml}

export DM_DYNOMITE_INTRA_CLUSTER_SECURITY=${DM_DYNOMITE_INTRA_CLUSTER_SECURITY:-none}

export DM_DYNOMITE_AUTO_EJECT_HOSTS=${DM_DYNOMITE_AUTO_EJECT_HOSTS:-true}

export DM_DYNOMITE_PEM_KEY_FILE=${DM_DYNOMITE_PEM_KEY_FILE:-/etc/dynomite/dynomite.pem}

# Cassandra Cluster for token management
# ======================================

export DM_CASSANDRA_CLUSTER_NAME=${DM_CASSANDRA_CLUSTER_NAME:-dynomite_manager}

export DM_CASSANDRA_KEYSPACE_NAME=${DM_CASSANDRA_KEYSPACE_NAME:-dyno_bootstrap}

export DM_CASSANDRA_THRIFT_PORT=${DM_CASSANDRA_THRIFT_PORT:-9160}

export DM_CASSANDRA_SEEDS=${DM_CASSANDRA_SEEDS:-127.0.0.1}

export DM_DYNOMITE_READ_CONSISTENCY=${DM_DYNOMITE_READ_CONSISTENCY:-DC_ONE}

export DM_DYNOMITE_WRITE_CONSISTENCY=${DM_DYNOMITE_WRITE_CONSISTENCY:-DC_ONE}

export DM_DATASTORE_MAX_MEMORY_PERCENT=${DM_DATASTORE_MAX_MEMORY_PERCENT:-85}

export DM_DATASTORE_ENGINE=${DM_DATASTORE_ENGINE:-redis}

# Data store: Redis
# =================

export DM_REDIS_CONF=${DM_REDIS_CONF:-/etc/redis/redis.conf}

export DM_REDIS_DATA_DIR=${DM_REDIS_DATA_DIR:-/var/lib/redis/}

export DM_REDIS_PERSISTENCE_ENABLED=${DM_REDIS_PERSISTENCE_ENABLED:-true}

export DM_REDIS_PERSISTENCE_TYPE=${DM_REDIS_PERSISTENCE_TYPE:-aof}

export DM_REDIS_START_SCRIPT=${DM_REDIS_START_SCRIPT:-/usr/sbin/service redis-server start}

export DM_REDIS_STOP_SCRIPT=${DM_REDIS_STOP_SCRIPT:-/usr/sbin/service redis-server stop}


# Warm up
# =======
export DM_DYNO_WARM_FORCE=${DM_DYNO_WARM_FORCE:-false}
export DM_DYNO_WARM_BOOTSTRAP=${DM_DYNO_WARM_BOOTSTRAP:-false}
export DM_DYNO_WARM_BYTES_SYNC_DIFF=${DM_DYNO_WARM_BYTES_SYNC_DIFF:-100000}
export DM_DYNO_WARM_MSEC_BOOTSTRAPTIME=${DM_DYNO_WARM_MSEC_BOOTSTRAPTIME:-900000}

# Backup and Restore
# ==================
export DM_DYNO_BACKUP_SNAPSHOT_ENABLED=${DM_DYNO_BACKUP_SNAPSHOT_ENABLED:-false}
# S3 bucket name to store backup files
export DM_DYNO_BACKUP_BUCKET_NAME=${DM_DYNO_BACKUP_BUCKET_NAME:-dynomite-backup}
export DM_DYNO_BACKUP_S3_BASE_DIR=${DM_DYNO_BACKUP_S3_BASE_DIR:-test-backup}
export DM_DYNO_BACKUP_HOUR=${DM_DYNO_BACKUP_HOUR:-12}
export DM_DYNO_BACKUP_SCHEDULE=${DM_DYNO_BACKUP_SCHEDULE:-day}
export DM_DYNO_BACKUP_RESTORE_ENABLED=${DM_DYNO_BACKUP_RESTORE_ENABLED:-false}
export DM_DYNO_BACKUP_RESTORE_DATE=${DM_DYNO_BACKUP_RESTORE_DATE:-20170601}

# Eureka
# ======

export DM_EUREKA_HOSTS_SUPPLIER_ENABLED=${DM_EUREKA_HOSTS_SUPPLIER_ENABLED:-false}
